seed: 1234
train_bs: 512
test_bs: 512
num_workers: 0
val_size: 0.2
balance_classes: True
frozen_encoder: True
backbone_name: resnet152
augmentations: flip
criterion: hinge

dataset:
  data_root: /home/rauf/Data/Ola
  meta_path: /home/rauf/Data/Ola/metadata/dataset_filtered.csv
  cmpds:
#    (1): [ 1.0, 0.3, 6.0, 3.0, 10.0 ]
#    (2): [ 10.0, 6.0, 1.0, 3.0, 0.3 ]
#    (3): [ 6.0, 10.0, 0.3, 1.0, 3.0 ]
#    (5): [ 3.0, 1.0, 6.0, 10.0, 0.3 ]
#    (6): [ 6.0, 3.0, 10.0, 0.3, 1.0 ]
#    (7): [ 10.0, 3.0, 1.0, 6.0, 0.3 ]
#    (o1): [ 6.0 ]
#    (o2): [ 6.0 ]
#    (o3): [ 6.0 ]
#    (o4): [ 6.0 ]
#    (o5): [ 6.0 ]
#    (sorbitol): [ 10.0, 6.0, 0.3, 1.0, 3.0 ]
#    "[M]": [ 3.0 ]
#    "[dmso]": [ 3.0 ]
#    "[e]": [ 3.0 ]
#    "[f]": [ 3.0 ]
    (1): [ 10.0 ]
    (2): [ 10.0 ]
    (3): [ 10.0 ]
    (5): [ 10.0 ]
    (6): [ 10.0 ]
    (7): [ 10.0 ]
    (o1): [ 6.0 ]
    (o2): [ 6.0 ]
    (o3): [ 6.0 ]
    (o4): [ 6.0 ]
    (o5): [ 6.0 ]
    (sorbitol): [ 10.0 ]
    "[M]": [ 3.0 ]
    "[dmso]": [ 3.0 ]
    "[e]": [ 3.0 ]
    "[f]": [ 3.0 ]

trainer:
  gpus: [2]
#  accelerator: dp
  checkpoint_callback: False
#  limit_train_batches: 3
#  limit_val_batches: 3
  max_epochs: 1000
